[package]
name = "srogue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.151"
ncurses = { version = "5.101.0", features = ["wide"] }
rand = "0.8.5"
