use crate::zap::wand_materials::WandMaterial;

pub const WANDS: usize = 10;
pub const MAX_WAND_MATERIAL: usize = 30;
pub const ALL_WAND_MATERIALS: [WandMaterial; MAX_WAND_MATERIAL] = [
	WandMaterial::STEEL,
	WandMaterial::BRONZE,
	WandMaterial::GOLD,
	WandMaterial::SILVER,
	WandMaterial::COPPER,
	WandMaterial::NICKEL,
	WandMaterial::COBALT,
	WandMaterial::TIN,
	WandMaterial::IRON,
	WandMaterial::MAGNESIUM,
	WandMaterial::CHROME,
	WandMaterial::CARBON,
	WandMaterial::PLATINUM,
	WandMaterial::SILICON,
	WandMaterial::TITANIUM,
	WandMaterial::TEAK,
	WandMaterial::OAK,
	WandMaterial::CHERRY,
	WandMaterial::BIRCH,
	WandMaterial::PINE,
	WandMaterial::CEDAR,
	WandMaterial::REDWOOD,
	WandMaterial::BALSA,
	WandMaterial::IVORY,
	WandMaterial::WALNUT,
	WandMaterial::MAPLE,
	WandMaterial::MAHOGANY,
	WandMaterial::ELM,
	WandMaterial::PALM,
	WandMaterial::WOODEN,
];
