use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Eq, PartialEq, Serialize, Deserialize)]
pub enum WandMaterial {
	STEEL,
	BRONZE,
	GOLD,
	SILVER,
	COPPER,
	NICKEL,
	COBALT,
	TIN,
	IRON,
	MAGNESIUM,
	CHROME,
	CARBON,
	PLATINUM,
	SILICON,
	TITANIUM,
	TEAK,
	OAK,
	CHERRY,
	BIRCH,
	PINE,
	CEDAR,
	REDWOOD,
	BALSA,
	IVORY,
	WALNUT,
	MAPLE,
	MAHOGANY,
	ELM,
	PALM,
	WOODEN,
}

impl WandMaterial {
	pub const fn is_wood(&self) -> bool {
		match self {
			WandMaterial::STEEL => false,
			WandMaterial::BRONZE => false,
			WandMaterial::GOLD => false,
			WandMaterial::SILVER => false,
			WandMaterial::COPPER => false,
			WandMaterial::NICKEL => false,
			WandMaterial::COBALT => false,
			WandMaterial::TIN => false,
			WandMaterial::IRON => false,
			WandMaterial::MAGNESIUM => false,
			WandMaterial::CHROME => false,
			WandMaterial::CARBON => false,
			WandMaterial::PLATINUM => false,
			WandMaterial::SILICON => false,
			WandMaterial::TITANIUM => false,
			WandMaterial::TEAK => true,
			WandMaterial::OAK => true,
			WandMaterial::CHERRY => true,
			WandMaterial::BIRCH => true,
			WandMaterial::PINE => true,
			WandMaterial::CEDAR => true,
			WandMaterial::REDWOOD => true,
			WandMaterial::BALSA => true,
			WandMaterial::IVORY => true,
			WandMaterial::WALNUT => true,
			WandMaterial::MAPLE => true,
			WandMaterial::MAHOGANY => true,
			WandMaterial::ELM => true,
			WandMaterial::PALM => true,
			WandMaterial::WOODEN => true,
		}
	}
	pub const fn name(&self) -> &'static str {
		match self {
			WandMaterial::STEEL => "steel ",
			WandMaterial::BRONZE => "bronze ",
			WandMaterial::GOLD => "gold ",
			WandMaterial::SILVER => "silver ",
			WandMaterial::COPPER => "copper ",
			WandMaterial::NICKEL => "nickel ",
			WandMaterial::COBALT => "cobalt ",
			WandMaterial::TIN => "tin ",
			WandMaterial::IRON => "iron ",
			WandMaterial::MAGNESIUM => "magnesium ",
			WandMaterial::CHROME => "chrome ",
			WandMaterial::CARBON => "carbon ",
			WandMaterial::PLATINUM => "platinum ",
			WandMaterial::SILICON => "silicon ",
			WandMaterial::TITANIUM => "titanium ",
			WandMaterial::TEAK => "teak ",
			WandMaterial::OAK => "oak ",
			WandMaterial::CHERRY => "cherry ",
			WandMaterial::BIRCH => "birch ",
			WandMaterial::PINE => "pine ",
			WandMaterial::CEDAR => "cedar ",
			WandMaterial::REDWOOD => "redwood ",
			WandMaterial::BALSA => "balsa ",
			WandMaterial::IVORY => "ivory ",
			WandMaterial::WALNUT => "walnut ",
			WandMaterial::MAPLE => "maple ",
			WandMaterial::MAHOGANY => "mahogany ",
			WandMaterial::ELM => "elm ",
			WandMaterial::PALM => "palm ",
			WandMaterial::WOODEN => "wooden "
		}
	}
}