use serde::{Deserialize, Serialize};
use crate::monster::MonsterFlags;
use crate::objects::{obj, object};
use crate::prelude::object_what::ObjectWhat;

#[derive(Copy, Clone, Serialize, Deserialize)]
pub enum MonsterType {
	Aquator,
	Bat,
	Centaur,
	Dragon,
	Emu,
	FlyTrap,
	Griffin,
	Hobgoblin,
	IceMonster,
	Jabberwock,
	Kestrel,
	Leprechaun,
	Medusa,
	Nymph,
	Orc,
	Phantom,
	Quagga,
	Rattlesnake,
	Snake,
	Troll,
	Unicorn,
	Vampire,
	Wraith,
	Xeroc,
	Yeti,
	Zombie,
}

impl From<usize> for MonsterType {
	fn from(value: usize) -> Self { MonsterType::LIST[value] }
}

impl MonsterType {
	pub fn first_level(&self) -> usize { MONSTER_TABLE[self.index()].first_level() }
	pub fn last_level(&self) -> usize { MONSTER_TABLE[self.index()].last_level() }
	pub fn create(&self) -> object { MONSTER_TABLE[self.index()].clone() }
	pub fn name(&self) -> &'static str {
		match self {
			MonsterType::Aquator => "aquator",
			MonsterType::Bat => "bat",
			MonsterType::Centaur => "centaur",
			MonsterType::Dragon => "dragon",
			MonsterType::Emu => "emu",
			MonsterType::FlyTrap => "venus fly-trap",
			MonsterType::Griffin => "griffin",
			MonsterType::Hobgoblin => "hobgoblin",
			MonsterType::IceMonster => "ice monster",
			MonsterType::Jabberwock => "jabberwock",
			MonsterType::Kestrel => "kestrel",
			MonsterType::Leprechaun => "leprechaun",
			MonsterType::Medusa => "medusa",
			MonsterType::Nymph => "nymph",
			MonsterType::Orc => "orc",
			MonsterType::Phantom => "phantom",
			MonsterType::Quagga => "quagga",
			MonsterType::Rattlesnake => "rattlesnake",
			MonsterType::Snake => "snake",
			MonsterType::Troll => "troll",
			MonsterType::Unicorn => "black unicorn",
			MonsterType::Vampire => "vampire",
			MonsterType::Wraith => "wraith",
			MonsterType::Xeroc => "xeroc",
			MonsterType::Yeti => "yeti",
			MonsterType::Zombie => "zombie",
		}
	}
	pub fn index(&self) -> usize {
		match self {
			MonsterType::Aquator => 0,
			MonsterType::Bat => 1,
			MonsterType::Centaur => 2,
			MonsterType::Dragon => 3,
			MonsterType::Emu => 4,
			MonsterType::FlyTrap => 5,
			MonsterType::Griffin => 6,
			MonsterType::Hobgoblin => 7,
			MonsterType::IceMonster => 8,
			MonsterType::Jabberwock => 9,
			MonsterType::Kestrel => 10,
			MonsterType::Leprechaun => 11,
			MonsterType::Medusa => 12,
			MonsterType::Nymph => 13,
			MonsterType::Orc => 14,
			MonsterType::Phantom => 15,
			MonsterType::Quagga => 16,
			MonsterType::Rattlesnake => 17,
			MonsterType::Snake => 18,
			MonsterType::Troll => 19,
			MonsterType::Unicorn => 20,
			MonsterType::Vampire => 21,
			MonsterType::Wraith => 22,
			MonsterType::Xeroc => 23,
			MonsterType::Yeti => 24,
			MonsterType::Zombie => 25,
		}
	}
	pub const LIST: [MonsterType; 26] = [
		MonsterType::Aquator, MonsterType::Bat, MonsterType::Centaur, MonsterType::Dragon, MonsterType::Emu, MonsterType::FlyTrap,
		MonsterType::Griffin, MonsterType::Hobgoblin, MonsterType::IceMonster, MonsterType::Jabberwock, MonsterType::Kestrel, MonsterType::Leprechaun,
		MonsterType::Medusa, MonsterType::Nymph, MonsterType::Orc, MonsterType::Phantom, MonsterType::Quagga, MonsterType::Rattlesnake,
		MonsterType::Snake, MonsterType::Troll, MonsterType::Unicorn, MonsterType::Vampire, MonsterType::Wraith, MonsterType::Xeroc,
		MonsterType::Yeti, MonsterType::Zombie,
	];
}

const MONSTER_TABLE: [object; 26] = [
	obj {
		m_flags: MonsterFlags::a(),
		quantity: 25,
		ichar: 'A',
		kill_exp: 20,
		is_protected: 9,
		is_cursed: 18,
		class: 100,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::b(),
		quantity: 10,
		ichar: 'B',
		kill_exp: 2,
		is_protected: 1,
		is_cursed: 8,
		class: 60,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::c(),
		quantity: 32,
		ichar: 'C',
		kill_exp: 15,
		is_protected: 7,
		is_cursed: 16,
		class: 85,
		identified: false,
		stationary_damage: 0,
		which_kind: 10,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::d(),
		quantity: 145,
		ichar: 'D',
		kill_exp: 5000,
		is_protected: 21,
		is_cursed: 126,
		class: 100,
		identified: false,
		stationary_damage: 0,
		which_kind:
		90,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::e(),
		quantity: 11,
		ichar: 'E',
		kill_exp: 2,
		is_protected: 1,
		is_cursed: 7,
		class: 65,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::f(),
		quantity: 73,
		ichar: 'F',
		kill_exp: 91,
		is_protected: 12,
		is_cursed: 126,
		class: 80,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::g(),
		quantity: 115,
		ichar: 'G',
		kill_exp: 2000,
		is_protected: 20,
		is_cursed: 126,
		class: 85,
		identified: false,
		stationary_damage: 0,
		which_kind:
		10,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::h(),
		quantity: 15,
		ichar: 'H',
		kill_exp: 3,
		is_protected: 1,
		is_cursed: 10,
		class: 67,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::i(),
		quantity: 15,
		ichar: 'I',
		kill_exp: 5,
		is_protected: 2,
		is_cursed: 11,
		class: 68,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::j(),
		quantity: 132,
		ichar: 'J',
		kill_exp: 3000,
		is_protected: 21,
		is_cursed: 126,
		class: 100,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::k(),
		quantity: 10,
		ichar: 'K',
		kill_exp: 2,
		is_protected: 1,
		is_cursed: 6,
		class: 60,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::l(),
		quantity: 25,
		ichar: 'L',
		kill_exp: 21,
		is_protected: 6,
		is_cursed: 16,
		class: 75,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::m(),
		quantity: 97,
		ichar: 'M',
		kill_exp: 250,
		is_protected: 18,
		is_cursed: 126,
		class: 85,
		identified: false,
		stationary_damage: 0,
		which_kind:
		25,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::n(),
		quantity: 25,
		ichar: 'N',
		kill_exp: 39,
		is_protected: 10,
		is_cursed: 19,
		class: 75,
		identified: false,
		stationary_damage: 0,
		which_kind:
		100,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::o(),
		quantity: 25,
		ichar: 'O',
		kill_exp: 5,
		is_protected: 4,
		is_cursed: 13,
		class: 70,
		identified: false,
		stationary_damage: 0,
		which_kind:
		10,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::p(),
		quantity: 76,
		ichar: 'P',
		kill_exp: 120,
		is_protected: 15,
		is_cursed: 24,
		class: 80,
		identified: false,
		stationary_damage: 0,
		which_kind:
		50,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::q(),
		quantity: 30,
		ichar: 'Q',
		kill_exp: 20,
		is_protected: 8,
		is_cursed: 17,
		class: 78,
		identified: false,
		stationary_damage: 0,
		which_kind:
		20,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::r(),
		quantity: 19,
		ichar: 'R',
		kill_exp: 10,
		is_protected: 3,
		is_cursed: 12,
		class: 70,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::s(),
		quantity: 8,
		ichar: 'S',
		kill_exp: 2,
		is_protected: 1,
		is_cursed: 9,
		class: 50,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::t(),
		quantity: 75,
		ichar: 'T',
		kill_exp: 125,
		is_protected: 13,
		is_cursed: 22,
		class: 75,
		identified: false,
		stationary_damage: 0,
		which_kind:
		33,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::u(),
		quantity: 90,
		ichar: 'U',
		kill_exp: 200,
		is_protected: 17,
		is_cursed: 26,
		class: 85,
		identified: false,
		stationary_damage: 0,
		which_kind:
		33,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::v(),
		quantity: 55,
		ichar: 'V',
		kill_exp: 350,
		is_protected: 19,
		is_cursed: 126,
		class: 85,
		identified: false,
		stationary_damage: 0,
		which_kind:
		18,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::w(),
		quantity: 45,
		ichar: 'W',
		kill_exp: 55,
		is_protected: 14,
		is_cursed: 23,
		class: 75,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::x(),
		quantity: 42,
		ichar: 'X',
		kill_exp: 110,
		is_protected: 16,
		is_cursed: 25,
		class: 75,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::y(),
		quantity: 35,
		ichar: 'Y',
		kill_exp: 50,
		is_protected: 11,
		is_cursed: 20,
		class: 80,
		identified: false,
		stationary_damage: 0,
		which_kind:
		20,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
	obj {
		m_flags: MonsterFlags::z(),
		quantity: 21,
		ichar: 'Z',
		kill_exp: 8,
		is_protected: 5,
		is_cursed: 14,
		class: 69,
		identified: false,
		stationary_damage: 0,
		which_kind: 0,
		o_row: 0,
		o_col: 0,
		o: 0,
		row: 0,
		col: 0,
		d_enchant: 0,
		quiver: 0,
		trow: 0,
		tcol: 0,
		hit_enchant: 0,
		what_is: ObjectWhat::None,
		disguise: 0,
		picked_up: 0,
		in_use_flags: 0,
		next_object: 0 as *const obj as *mut obj,
	},
];
